import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  ne: {
    home: 'गृह', products: 'उत्पादनहरू', categories: 'श्रेणीहरू',
    about: 'हाम्रो बारेमा', contact: 'सम्पर्क', cart: 'कार्ट',
    login: 'लगइन', register: 'दर्ता', logout: 'बाहिर निस्कनुहोस्',
    search: 'खोज्नुहोस्', addToCart: 'कार्टमा थप्नुहोस्',
    outOfStock: 'स्टक छैन', viewDetails: 'विवरण हेर्नुहोस्',
    price: 'मूल्य', total: 'कुल', checkout: 'चेकआउट',
    myOrders: 'मेरा अर्डरहरू', profile: 'प्रोफाइल',
    heroTitle: 'स्मार्ट जीवन, सरलीकृत', heroSubtitle: 'घरेलु उपकरणहरू सबैभन्दा राम्रो मूल्यमा',
    shopNow: 'अहिले खरिद गर्नुहोस्', featuredProducts: 'चुनिएका उत्पादनहरू',
    whyChooseUs: 'हामीलाई किन छनौट गर्ने', emptyCart: 'तपाईंको कार्ट खाली छ',
    continueShopping: 'खरिदारी जारी राख्नुहोस्', quantity: 'मात्रा',
    remove: 'हटाउनुहोस्', subtotal: 'उप-योग', shipping: 'ढुवानी',
    placeOrder: 'अर्डर गर्नुहोस्', cod: 'नगद भुक्तानी',
    online: 'अनलाइन भुक्तानी', shippingAddress: 'ढुवानी ठेगाना',
    paymentMethod: 'भुक्तानी विधि', orderSummary: 'अर्डर सारांश',
    specifications: 'विनिर्देशहरू', features: 'विशेषताहरू',
    reviews: 'समीक्षाहरू', pending: 'विचाराधीन', confirmed: 'पुष्टि भयो',
    processing: 'प्रक्रियामा', shipped: 'पठाइयो', delivered: 'डेलिभर भयो',
    cancelled: 'रद्द भयो', save: 'सुरक्षित गर्नुहोस्', cancel: 'रद्द गर्नुहोस्',
    edit: 'सम्पादन', delete: 'मेटाउनुहोस्', loading: 'लोड हुँदैछ...',
    loginTitle: 'लगइन', email: 'इमेल', password: 'पासवर्ड',
    loginBtn: 'लगइन गर्नुहोस्', noAccount: 'खाता छैन?',
    registerTitle: 'दर्ता', fullName: 'पूरा नाम', phone: 'फोन',
    registerBtn: 'दर्ता गर्नुहोस्', haveAccount: 'पहिले नै खाता छ?',
    orderPlaced: 'अर्डर सफलतापूर्वक राखियो!', orderId: 'अर्डर नम्बर',
    viewOrder: 'अर्डर हेर्नुहोस्', orderTitle: 'अर्डर',
    status: 'स्थिति', payment: 'भुक्तानी', date: 'मिति', items: 'सामानहरू',
    aboutTitle: 'ELVORA को बारेमा',
    aboutSubtitle: 'स्मार्ट जीवन, सरलीकृत — सबैका लागि आधुनिक खरिद अनुभव',
    whoWeAre: 'हामी को हौं',
    whoWeAreDesc1: 'ELVORA एक अत्याधुनिक इ-कमर्स प्लेटफर्म हो जसले अनलाइन खरिदलाई सरल, द्रुत र भरपर्दो बनाउँछ।',
    whoWeAreDesc2: 'हाम्रो लक्ष्य एउटा विश्वसनीय इकोसिस्टम बनाउनु हो जहाँ ग्राहकहरूले आत्मविश्वासपूर्वक खरिद गर्न सकुन्।',
    missionTitle: 'हाम्रो उद्देश्य',
    missionDesc: 'प्रविधि, विश्वास र नवीनतालाई मिलाएर अनलाइन खरिदलाई सरल बनाउनु — प्रत्येकका लागि दैनिक खरिदलाई सहज र आनन्ददायी बनाउनु।',
    valuesTitle: 'हाम्रा मूल्यहरू',
    trust: 'विश्वास', trustDesc: 'हामी प्रत्येक कारोबारमा पारदर्शिता र भरपर्दोपनालाई प्राथमिकता दिन्छौं।',
    quality: 'गुणस्तर', qualityDesc: 'ग्राहकसम्म पुग्नु अघि हामी सुनिश्चित गर्छौं कि प्रत्येक उत्पादन उच्च मापदण्डको छ।',
    innovation: 'नवीनता', innovationDesc: 'राम्रो खरिद अनुभव दिनका लागि हामी निरन्तर सुधार गर्दैछौं।',
    ctaTitle: 'आफ्नो खरिद यात्रा सुरु गर्नुहोस्',
    ctaSubtitle: 'आधुनिक जीवनका लागि डिजाइन गरिएका उत्पादनहरू पत्ता लगाउनुहोस्।',
    exploreProducts: 'उत्पादनहरू हेर्नुहोस्',
    products100: '१०० भन्दा बढी उत्पादनहरू', support247: '२४/७ सेवा',
    fastDelivery: 'द्रुत डेलिभरी', securePayment: 'सुरक्षित भुक्तानी',
    faqTitle: 'बारम्बार सोधिने प्रश्नहरू',
    faqSubtitle: 'ELVORA बारे तपाईंलाई चाहिने सबै जानकारी',
    faqQ1: 'डेलिभरी कति दिनमा हुन्छ?',
    faqA1: 'तपाईंको स्थानअनुसार डेलिभरी सामान्यतः ३–७ कार्यदिनमा हुन्छ।',
    faqQ2: 'कुन-कुन भुक्तानी विधिहरू उपलब्ध छन्?',
    faqA2: 'हामी UPI, कार्ड, नेट ब्याङ्किङ र नगद भुक्तानी स्वीकार गर्छौं।',
    faqQ3: 'के उत्पादन फिर्ता गर्न सकिन्छ?',
    faqA3: 'हो, डेलिभरीको ७ दिनभित्र फिर्ता शर्तहरू पूरा भएमा उत्पादन फिर्ता गर्न सकिन्छ।',
    faqQ4: 'मेरो अर्डर कसरी ट्र्याक गर्ने?',
    faqA4: '"मेरा अर्डरहरू" खण्डमा जानुस् र ट्र्याकिङ विवरणका लागि जुनसुकै अर्डरमा क्लिक गर्नुहोस्।',
    faqQ5: 'के मेरो भुक्तानी सुरक्षित छ?',
    faqA5: 'हो, सबै भुक्तानीहरू इन्क्रिप्ट गरिएको र सुरक्षित गेटवे मार्फत प्रक्रिया गरिन्छ।',
    shippingTitle: 'ढुवानी र डेलिभरी',
    shippingSubtitle: 'द्रुत, सुरक्षित र भरपर्दो डेलिभरी',
    deliveryTime: '📦 डेलिभरी समय',
    deliveryTimeDesc: 'अर्डरहरू सामान्यतः तपाईंको स्थानअनुसार ३–७ कार्यदिनमा डेलिभर हुन्छ। दुर्गम क्षेत्रहरूमा अलि बढी समय लाग्न सक्छ।',
    shippingCharges: '💰 ढुवानी शुल्क',
    shippingChargesDesc: 'चयनित उत्पादनहरूमा निःशुल्क ढुवानी उपलब्ध छ। अन्य सामानहरूमा चेकआउटमा न्यूनतम ढुवानी शुल्क लागू हुन्छ।',
    orderTracking: '📍 अर्डर ट्र्याकिङ',
    orderTrackingDesc: '"मेरा अर्डरहरू" खण्डबाट तपाईं जुनसुकै समय अर्डर ट्र्याक गर्न सक्नुहुन्छ। अर्डर पठाइएपछि रियल-टाइम अपडेट प्रदान गरिन्छ।',
    packagingSafety: '📦 प्याकेजिङ सुरक्षा',
    packagingSafetyDesc: 'सबै उत्पादनहरू क्षतिरहित तपाईंसम्म पुग्ने गरी सुरक्षित रूपमा प्याक गरिन्छ।',
    needHelp: 'तपाईंको अर्डरमा सहायता चाहिन्छ?',
    contactSupport: 'सहायता सम्पर्क', visitFaq: 'FAQ हेर्नुहोस्',
    supportTitle: 'सहायता र समर्थन',
    supportSubtitle: 'हामी जहिले पनि तपाईंलाई सहायता गर्न तयार छौं',
    emailSupport: 'इमेल', emailSupportDesc: 'इमेल मार्फत सहायता प्राप्त गर्नुहोस्',
    callSupport: 'फोन', callSupportDesc: 'सहायता टोलीसँग कुरा गर्नुहोस्',
    whatsapp: 'WhatsApp', whatsappDesc: 'तुरुन्त च्याट गर्नुहोस्',
    serviceCenters: 'सेवा केन्द्रहरू', serviceCentersDesc: 'नजिकको सहायता खोज्नुहोस्',
    howCanWeHelp: 'हामी कसरी सहायता गर्न सक्छौं?',
    orderIssues: 'अर्डर समस्याहरू', orderIssuesDesc: 'तपाईंको अर्डर ट्र्याक, रद्द वा समस्या रिपोर्ट गर्नुहोस्।',
    paymentHelp: 'भुक्तानी सहायता', paymentHelpDesc: 'भुक्तानी असफलता वा फिर्ता सम्बन्धी प्रश्नहरू समाधान गर्नुहोस्।',
    deliverySupport: 'डेलिभरी सहायता', deliverySupportDesc: 'ढिलो वा हराएको डेलिभरीको अद्यावधिक जानकारी पाउनुहोस्।',
    returnsRefunds: 'फिर्ता र रिफन्ड', returnsRefundsDesc: 'उत्पादन फिर्ता र रिफन्ड स्थितिमा सहायता।',
    immediateHelp: 'तत्काल सहायता चाहिन्छ?',
    immediateHelpDesc: 'हाम्रो सहायता टोलीसँग सम्पर्क गर्नुहोस् वा अर्डर हेर्नुहोस्',
    contactSupportBtn: 'सहायता सम्पर्क', viewMyOrders: 'मेरा अर्डरहरू हेर्नुहोस्',
    lookingAnswers: 'उत्तर खोज्दै हुनुहुन्छ?', visitFAQ: 'FAQ पृष्ठ हेर्नुहोस्',
    serviceCenterTitle: 'सेवा केन्द्रहरू', serviceCenterSubtitle: 'तपाईंको नजिकको ELVORA सहायता खोज्नुहोस्',
    returnsTitle: 'फिर्ता नीति', returnsSubtitle: 'ELVORA मा सहज र पारदर्शी फिर्ता प्रक्रिया',
    returnEligibility: '१. फिर्ता योग्यता', returnEligibilityDesc: 'डेलिभरीको ७ दिनभित्र उत्पादन फिर्ता योग्य छ। सामान मूल अवस्थामा, सबै प्याकेजिङ, ट्याग र एक्सेसरीजसहित हुनुपर्छ।',
    nonReturnable: '२. फिर्ता अयोग्य सामानहरू', nonReturnableDesc: 'प्रयोग भएका सामान, व्यक्तिगत हेरचाह सामान वा क्लियरेन्स सेल सामानहरू फिर्ता योग्य छैनन्।',
    returnConditions: '३. फिर्ता शर्तहरू', returnConditionsDesc: 'सामान अप्रयुक्त, अनधोएको र मूल प्याकेजिङमा हुनुपर्छ। क्षतिग्रस्त वा परिवर्तन गरिएका सामान स्वीकार नहुन सक्छ।',
    returnProcess: '४. फिर्ता प्रक्रिया', returnProcessDesc: 'फिर्ता सुरु गर्न "मेरा अर्डरहरू" खण्डमा जानुहोस् वा ग्राहक सहायतासँग सम्पर्क गर्नुहोस्। स्वीकृत भएपछि तपाईंको ठाउँबाट पिकअप व्यवस्था मिलाइनेछ।',
    refundTimeline: '५. रिफन्ड समयरेखा', refundTimelineDesc: 'फिर्ता भएका उत्पादनको सफल निरीक्षणपछि, मूल भुक्तानी विधिमा ५–७ कार्यदिनभित्र रिफन्ड प्रक्रिया हुनेछ।',
    cancellationTitle: 'अर्डर रद्द नीति', cancellationSubtitle: 'ELVORA अर्डर कसरी र कहिले रद्द गर्न सकिन्छ जान्नुहोस्',
    cancelBeforeShipping: '१. ढुवानीभन्दा अघि रद्द', cancelBeforeShippingDesc: 'अर्डर हाम्रो गोदामबाट प्रक्रिया वा पठाइनुभन्दा अघि जुनसुकै समय रद्द गर्न सकिन्छ। रद्द सफल भएपछि पूर्ण रिफन्ड सुरु गरिनेछ।',
    cancelAfterShipping: '२. ढुवानीपछि रद्द', cancelAfterShippingDesc: 'अर्डर पठाइसकेपछि रद्द गर्न मिल्दैन। तर उत्पादन प्राप्त गरेपछि फिर्ता अनुरोध गर्न सकिन्छ।',
    cancelTimeWindow: '३. रद्द समय सीमा', cancelTimeWindowDesc: 'उत्पादनको स्थिति र उपलब्धताअनुसार अर्डर राखेपछि सीमित समयभित्र मात्र रद्द अनुरोध स्वीकार गरिन्छ।',
    refundProcess: '४. रिफन्ड प्रक्रिया', refundProcessDesc: 'योग्य भएमा, रद्द स्वीकृतिपछि ५–७ कार्यदिनभित्र मूल भुक्तानी विधिमा रिफन्ड प्रक्रिया हुनेछ।',
    nonCancellable: '५. रद्द अयोग्य सामानहरू', nonCancellableDesc: 'अनुकूलित उत्पादन वा क्लियरेन्स सेल सामान जस्ता केही सामानहरू रद्दका लागि योग्य नहुन सक्छन्।',
    termsTitle: 'सेवा सर्तहरू', termsSubtitle: 'ELVORA प्रयोग गर्नुअघि कृपया यी सर्तहरू ध्यानपूर्वक पढ्नुहोस्',
    termsAcceptance: '१. सर्त स्वीकृति', termsAcceptanceDesc: 'ELVORA प्लेटफर्म पहुँच वा प्रयोग गरेर, तपाईं यी सेवा सर्तहरूमा बाँधिन सहमत हुनुहुन्छ।',
    termsEligibility: '२. प्रयोगकर्ता योग्यता', termsEligibilityDesc: 'हाम्रो प्लेटफर्म प्रयोग गर्न तपाईंको उमेर कम्तीमा १८ वर्ष वा अभिभावकको सहमति हुनुपर्छ।',
    termsOrders: '३. अर्डर र भुक्तानी', termsOrdersDesc: 'ELVORA मा राखिएका सबै अर्डरहरू उपलब्धता र पुष्टिमा निर्भर हुन्छन्। मूल्यहरू पूर्व सूचनाबिना परिवर्तन हुन सक्छन्।',
    termsProduct: '४. उत्पादन जानकारी', termsProductDesc: 'हामी सबै उत्पादन विवरणहरू सही राख्ने प्रयास गर्छौं, तर थोरै भिन्नता हुन सक्छ। तस्बिरहरू प्रतिनिधित्वका लागि मात्र हुन्।',
    termsProhibited: '५. निषेधित प्रयोग', termsProhibitedDesc: 'प्रयोगकर्ताहरूले अवैध गतिविधि, धोखाधडी वा अनाधिकृत पहुँचका लागि प्लेटफर्म दुरुपयोग गर्नु हुँदैन।',
    privacyTitle: 'गोपनीयता नीति', privacySubtitle: 'ELVORA मा तपाईंको गोपनीयता हाम्रो प्राथमिकता हो',
    privacyCollect: '१. हामीले के जानकारी सङ्कलन गर्छौं', privacyCollectDesc: 'अर्डर राख्दा वा ELVORA मा दर्ता गर्दा हामी नाम, इमेल, फोन नम्बर, ढुवानी ठेगाना र भुक्तानी विवरण जस्ता व्यक्तिगत जानकारी सङ्कलन गर्छौं।',
    privacyUse: '२. हामी जानकारी कसरी प्रयोग गर्छौं', privacyUseDesc: 'तपाईंको जानकारी अर्डर प्रक्रिया, ग्राहक सहायता र सेवा सुधारका लागि प्रयोग गरिन्छ।',
    privacyProtection: '३. डेटा सुरक्षा', privacyProtectionDesc: 'तपाईंको डेटालाई अनाधिकृत पहुँचबाट जोगाउन हामी सुरक्षित सर्भर र एन्क्रिप्सन विधिहरू प्रयोग गर्छौं।',
    privacySharing: '४. जानकारी साझेदारी', privacySharingDesc: 'हामी तपाईंको व्यक्तिगत डेटा बेच्दैनौं। जानकारी केवल विश्वसनीय सेवा साझेदारहरूसँग मात्र साझा गरिन्छ।',
    privacyCookies: '५. कुकिज र ट्र्याकिङ', privacyCookiesDesc: 'प्रयोगकर्ता अनुभव सुधार गर्न र सामग्री व्यक्तिगत बनाउन हामी कुकिज प्रयोग गर्छौं।',
    footerTagline: 'स्मार्ट जीवन, सरलीकृत',
    quickLinks: 'द्रुत लिङ्कहरू',
    myAccount: 'मेरो खाता',
    supportFooter: 'सहायता',
    contactUs: 'सम्पर्क गर्नुहोस्',
    faqShort: 'प्रश्नोत्तर',
    shippingShort: 'ढुवानी',
    helpSupport: 'सहायता केन्द्र',
    serviceCentersShort: 'सेवा केन्द्रहरू',
    termsAndPolicies: 'सर्त र नीतिहरू',
    termsOfService: 'सेवा सर्तहरू',
    privacyPolicy: 'गोपनीयता नीति',
    returnPolicy: 'फिर्ता नीति',
    orderCancellation: 'अर्डर रद्द',
    servicesFooter: 'सेवाहरू',
    copyright: '© 2025 ELVORA. सर्वाधिकार सुरक्षित।',

    manageInfo: "आफ्नो व्यक्तिगत जानकारी व्यवस्थापन गर्नुहोस्",

addresses: 'ठेगानाहरू',
addAddress: 'ठेगाना थप्नुहोस्',
noAddresses: 'कुनै ठेगाना छैन',
setDefault: 'डिफल्ट सेट गर्नुहोस्',
defaultLabel: 'डिफल्ट',
editAddress: 'ठेगाना सम्पादन',
addAddressTitle: 'ठेगाना थप्नुहोस्',
addressLine1: 'ठेगाना लाइन १',
addressLine2: 'ठेगाना लाइन २ (ऐच्छिक)',
city: 'सहर',
state: 'राज्य',
zipCode: 'जिप कोड',
labelHome: 'घर',
labelWork: 'कार्यालय',
labelOther: 'अन्य',
  },

    
  en: {
    home: 'Home', products: 'Products', categories: 'Categories',
    about: 'About', contact: 'Contact', cart: 'Cart',
    login: 'Login', register: 'Register', logout: 'Logout',
    search: 'Search', addToCart: 'Add to Cart',
    outOfStock: 'Out of Stock', viewDetails: 'View Details',
    price: 'Price', total: 'Total', checkout: 'Checkout',
    myOrders: 'My Orders', profile: 'My Profile',
    heroTitle: 'Smart Living, Simplified', heroSubtitle: 'Home Appliances at Best Prices',
    shopNow: 'Shop Now', featuredProducts: 'Featured Products',
    whyChooseUs: 'Why Choose Us', emptyCart: 'Your cart is empty',
    continueShopping: 'Continue Shopping', quantity: 'Quantity',
    remove: 'Remove', subtotal: 'Subtotal', shipping: 'Shipping',
    placeOrder: 'Place Order', cod: 'Cash on Delivery',
    online: 'Online Payment', shippingAddress: 'Shipping Address',
    paymentMethod: 'Payment Method', orderSummary: 'Order Summary',
    specifications: 'Specifications', features: 'Features',
    reviews: 'Reviews', pending: 'Pending', confirmed: 'Confirmed',
    processing: 'Processing', shipped: 'Shipped', delivered: 'Delivered',
    cancelled: 'Cancelled', save: 'Save', cancel: 'Cancel',
    edit: 'Edit', delete: 'Delete', loading: 'Loading...',
    loginTitle: 'Login', email: 'Email', password: 'Password',
    loginBtn: 'Login', noAccount: "Don't have an account?",
    registerTitle: 'Register', fullName: 'Full Name', phone: 'Phone',
    registerBtn: 'Register', haveAccount: 'Already have an account?',
    orderPlaced: 'Order Placed Successfully!', orderId: 'Order ID',
    viewOrder: 'View Order', orderTitle: 'Order',
    status: 'Status', payment: 'Payment', date: 'Date', items: 'Items',
    aboutTitle: 'About ELVORA',
    aboutSubtitle: 'Smart Living, Simplified — Building a modern shopping experience for everyone.',
    whoWeAre: 'Who We Are',
    whoWeAreDesc1: 'ELVORA is a next-generation e-commerce platform designed to make online shopping simple, fast, and reliable.',
    whoWeAreDesc2: 'Our goal is to create a trusted ecosystem where customers can shop with confidence and convenience.',
    missionTitle: 'Our Mission',
    missionDesc: 'To simplify online shopping by combining technology, trust, and innovation — making everyday shopping effortless and enjoyable for everyone.',
    valuesTitle: 'Our Values',
    trust: 'Trust', trustDesc: 'We prioritize transparency and reliability in every transaction.',
    quality: 'Quality', qualityDesc: 'We ensure every product meets high standards before reaching customers.',
    innovation: 'Innovation', innovationDesc: 'We constantly improve to deliver a better shopping experience.',
    ctaTitle: 'Start Your Shopping Journey',
    ctaSubtitle: 'Discover products designed for modern living.',
    exploreProducts: 'Explore Products',
    products100: '100+ Products', support247: '24/7 Support',
    fastDelivery: 'Fast Delivery', securePayment: 'Secure Payments',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Everything you need to know about ELVORA',
    faqQ1: 'How long does delivery take?',
    faqA1: 'Delivery usually takes 3–7 business days depending on your location.',
    faqQ2: 'What payment methods are available?',
    faqA2: 'We accept UPI, cards, net banking, and Cash on Delivery.',
    faqQ3: 'Can I return a product?',
    faqA3: 'Yes, you can return products within 7 days of delivery if they meet return conditions.',
    faqQ4: 'How can I track my order?',
    faqA4: 'Go to My Orders section and click on any order to view tracking details.',
    faqQ5: 'Is my payment secure?',
    faqA5: 'Yes, all payments are encrypted and processed through secure gateways.',
    shippingTitle: 'Shipping and Delivery',
    shippingSubtitle: 'Fast, safe & reliable delivery across Nepal',
    deliveryTime: '📦 Delivery Time',
    deliveryTimeDesc: 'Orders are usually delivered within 3–7 business days depending on your location. Remote areas may take slightly longer.',
    shippingCharges: '💰 Shipping Charges',
    shippingChargesDesc: 'We offer free shipping on selected products. For other items, minimal shipping charges are applied at checkout.',
    orderTracking: '📍 Order Tracking',
    orderTrackingDesc: 'You can track your order anytime from the My Orders section. Real-time updates are provided once your order is shipped.',
    packagingSafety: '📦 Packaging Safety',
    packagingSafetyDesc: 'All products are securely packed to ensure they reach you safely without damage.',
    needHelp: 'Need help with your order?',
    contactSupport: 'Contact Support', visitFaq: 'Visit FAQ',
    supportTitle: 'Help & Support',
    supportSubtitle: "We're here to help you anytime, anywhere",
    emailSupport: 'Email', emailSupportDesc: 'Get support via email',
    callSupport: 'Call', callSupportDesc: 'Talk to support team',
    whatsapp: 'WhatsApp', whatsappDesc: 'Chat instantly',
    serviceCenters: 'Service Centers', serviceCentersDesc: 'Find nearby help',
    howCanWeHelp: 'How can we help you?',
    orderIssues: 'Order Issues', orderIssuesDesc: 'Track, cancel, or report problems with your order.',
    paymentHelp: 'Payment Help', paymentHelpDesc: 'Resolve payment failures or refund related queries.',
    deliverySupport: 'Delivery Support', deliverySupportDesc: 'Get updates about delayed or missing deliveries.',
    returnsRefunds: 'Returns & Refunds', returnsRefundsDesc: 'Help with product returns and refund status.',
    immediateHelp: 'Need immediate help?',
    immediateHelpDesc: 'Contact our support team or check your orders',
    contactSupportBtn: 'Contact Support', viewMyOrders: 'View My Orders',
    lookingAnswers: 'Looking for answers?', visitFAQ: 'FAQ Page',
    serviceCenterTitle: 'Service Centers', serviceCenterSubtitle: 'Find ELVORA support near your city',
    returnsTitle: 'Return Policy', returnsSubtitle: 'Easy and transparent return process at ELVORA',
    returnEligibility: '1. Return Eligibility', returnEligibilityDesc: 'Products are eligible for return within 7 days of delivery. Items must be in original condition with all packaging, tags, and accessories intact.',
    nonReturnable: '2. Non-Returnable Items', nonReturnableDesc: 'Certain products such as used items, personal care goods, or clearance sale items are not eligible for return.',
    returnConditions: '3. Return Conditions', returnConditionsDesc: 'Items must be unused, unwashed, and in original packaging. Damaged or altered products may not be accepted.',
    returnProcess: '4. Return Process', returnProcessDesc: 'To initiate a return, go to "My Orders" section or contact customer support. Once approved, pickup will be arranged from your location.',
    refundTimeline: '5. Refund Timeline', refundTimelineDesc: 'After successful inspection of returned products, refunds will be processed within 5–7 business days to the original payment method.',
    cancellationTitle: 'Order Cancellation Policy', cancellationSubtitle: 'Learn how and when you can cancel your ELVORA orders',
    cancelBeforeShipping: '1. Cancellation Before Shipping', cancelBeforeShippingDesc: 'Orders can be cancelled anytime before they are processed or shipped. Once cancellation is requested, a full refund will be initiated.',
    cancelAfterShipping: '2. Cancellation After Shipping', cancelAfterShippingDesc: 'Once an order has been shipped, it cannot be cancelled. However, you may initiate a return request after receiving the product.',
    cancelTimeWindow: '3. Cancellation Time Window', cancelTimeWindowDesc: 'Cancellation requests are accepted only within a limited time window after order placement, depending on product status and availability.',
    refundProcess: '4. Refund Process', refundProcessDesc: 'If eligible, refunds will be processed to the original payment method within 5–7 business days after cancellation approval.',
    nonCancellable: '5. Non-Cancellable Items', nonCancellableDesc: 'Certain items such as customized products or clearance sale items may not be eligible for cancellation.',
    termsTitle: 'Terms of Service', termsSubtitle: 'Please read these terms carefully before using ELVORA',
    termsAcceptance: '1. Acceptance of Terms', termsAcceptanceDesc: 'By accessing or using the ELVORA platform, you agree to be bound by these Terms of Service.',
    termsEligibility: '2. User Eligibility', termsEligibilityDesc: 'You must be at least 18 years old or have parental consent to use our platform.',
    termsOrders: '3. Orders & Payments', termsOrdersDesc: 'All orders placed on ELVORA are subject to availability and confirmation. Prices may change without prior notice.',
    termsProduct: '4. Product Information', termsProductDesc: 'We try to ensure all product details are accurate, but slight variations may occur. Images are for representation purposes only.',
    termsProhibited: '5. Prohibited Use', termsProhibitedDesc: 'Users must not misuse the platform for illegal activities, fraud, or unauthorized access.',
    privacyTitle: 'Privacy Policy', privacySubtitle: 'Your privacy is important to us at ELVORA',
    privacyCollect: '1. Information We Collect', privacyCollectDesc: 'We collect personal information such as name, email address, phone number, shipping address, and payment details when you register on ELVORA.',
    privacyUse: '2. How We Use Your Information', privacyUseDesc: 'Your information is used to process orders, provide customer support, improve services, and communicate important updates.',
    privacyProtection: '3. Data Protection', privacyProtectionDesc: 'We use secure servers and encryption methods to protect your data from unauthorized access, misuse, or disclosure.',
    privacySharing: '4. Sharing of Information', privacySharingDesc: 'We do not sell or rent your personal data. Information may be shared only with trusted service partners such as delivery and payment providers.',
    privacyCookies: '5. Cookies & Tracking', privacyCookiesDesc: 'We use cookies to improve user experience, analyze website traffic, and personalize content based on user preferences.',
    footerTagline: 'Smart Living, Simplified',
    quickLinks: 'Quick Links',
    myAccount: 'My Account',
    supportFooter: 'Support',
    contactUs: 'Contact Us',
    faqShort: 'FAQ',
    shippingShort: 'Shipping',
    helpSupport: 'Help & Support',
    serviceCentersShort: 'Service Centers',
    termsAndPolicies: 'Terms & Policies',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    returnPolicy: 'Return Policy',
    orderCancellation: 'Order Cancellation',
    servicesFooter: 'Services',
    copyright: '© 2025 ELVORA. All rights reserved.',
    manageInfo: 'Manage your personal information',
addresses: 'Addresses',
addAddress: 'Add Address',
noAddresses: 'No addresses yet',
setDefault: 'Set Default',
defaultLabel: 'Default',
editAddress: 'Edit Address',
addAddressTitle: 'Add Address',
addressLine1: 'Address Line 1',
addressLine2: 'Address Line 2 (optional)',
city: 'City',
state: 'State',
zipCode: 'ZIP Code',
labelHome: 'Home',
labelWork: 'Work',
labelOther: 'Other',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('lang') || 'ne');
  useEffect(() => { localStorage.setItem('lang', language); }, [language]);
  const t = (key) => translations[language][key] || key;
  const changeLanguage = (lang) => setLanguage(lang);
  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => useContext(LanguageContext);
